- name: Update APT cache
  apt:
    update_cache: yes

- name: Upgrade the system
  apt:
    upgrade: dist

- name: Install essential packages
  apt:
    name:
      - apt-transport-https
      - ca-certificates
      - git
      - curl
      - unzip
      - zsh
      - python3
      - python3-pip
      - python3-venv
      - ufw
      - htop
      - fail2ban
      - net-tools
      - lsof
      - gnupg
      - software-properties-common
    state: present

- name: Set timezone
  timezone:
    name: Europe/Paris

- name: Change root shell to Zsh
  user:
    name: root
    shell: /bin/zsh