- name: Update APT cache
  apt:
    update_cache: yes
  become: true

- name: Upgrade the system
  apt:
    upgrade: dist
  become: true

- name: Install essential packages
  apt:
    name:
      - apt-transport-https
      - ca-certificates
      - git
      - curl
      - unzip
      - zsh
      - htop
    state: present
  become: true

- name: Set timezone
  timezone:
    name: Europe/Paris
  become: true

- name: Change root shell to Zsh
  user:
    name: root
    shell: /bin/zsh
  become: true