- name: Ensure remote Ansible temporary directory exists
  file:
    path: /tmp/ansible_tmp
    state: directory
    mode: '1777'
    owner: root
    group: root
  become: true

- name: Create the user account
  user:
    name: "{{ user_name }}"
    password: "{{ user_password_hashed }}"
    state: present
    groups: sudo
    append: yes
  become: true

- name: Create .ssh directory in the user's home
  file:
    path: /home/user/.ssh
    state: directory
    owner: user
    group: user
    mode: '0700'
  become: true

- name: Copy authorized_keys from root to user's .ssh directory
  copy:
    src: /root/.ssh/authorized_keys
    dest: /home/user/.ssh/authorized_keys
    owner: user
    group: user
    mode: '0600'
    remote_src: yes
  notify: Restart SSH service
